author: wizzledonker
database: false
description: A simple, lightweight block gaurding plugin with an easy to use API
main: me.wizzledonker.plugins.problockgaurd.ProBlockGaurd
name: ProBlockGaurd
startup: postworld
version: '1.0'